### ISSUE TITLE
 Error: "distro_bootcmd" not defined

### ISSUE THREAD

**Issue by kouzhentao** [hdlguy/zcu104_ubuntu#1]
Hi,

I exactly follow you guide and get the compilation result. But when boot from the sd card, I got the  error message:

** Unable to read file system.dtb **
## Error: "distro_bootcmd" not defined

I also generate the system.dtb(u said the optional step), and copy to sd card. 
can you please  give me some hints, 3x.

Kou

**Comment by hdlguy** [comment]
Hello Kou,

I did finally get a reliable boot of Ubuntu off the SD card but I have not fully updated the instructions.  I built the kernel, dtb, u-boot and boot.bin all through Petalinux.  I also used a different filesystem, Ubuntu 2018.04 LTS.

Also, I am not sure how to respond to messages from people on GitHub.  I hope you get this message.

  Pete
________________________________

**Comment by hdlguy** [comment]
Kou,

I'm glad someone is looking at my page.  Tonight or this weekend I should have time to update the instructions in my readme and give it another test run to make sure it works.

Regards

**Comment by hdlguy** [comment]
Kou,

I put simplified instructions here.

https://github.com/hdlguy/zcu104_ubuntu/blob/master/software/petalinux/readme.txt

I reran everything with a fresh SD card and it worked.


________________________________

**Comment by kouzhentao** [comment]
Hi Pete,

Great. thanks a lot for your reply. I will try today and update u. 3x again.

Kou

**Comment by kouzhentao** [comment]
Hi Pete，

I followed this petalinux guide,  it stuck at, can you please have a look, thanks.
[    4.475622] Waiting for root device /dev/mmcblk0p2...
[    5.551911] [drm] Cannot find any crtc or sizes

Kou

[    4.448935] dwc3: probe of fe200000.dwc3 failed with error -22
[    4.455518] rtc_zynqmp ffa60000.rtc: setting system clock to 2018-06-24 15:36:16 UTC (1529854576)
[    4.464401] clk: Not disabling unused clocks
[    4.468634] ALSA device list:
[    4.471536]   #0: DisplayPort monitor
[    4.475622] Waiting for root device /dev/mmcblk0p2...
[    5.551911] [drm] Cannot find any crtc or sizes
