### ISSUE TITLE
Decoding Error

### ISSUE THREAD

**Issue by yildizbilgin** [hdlguy/zcu104_ubuntu#3]
Hello,

Have you ever tried to decode and encode some videos after you create the project and boot the board? 

 I am trying to decode two 4K streams at the same time, but I get an error:

![fffffff](https://user-images.githubusercontent.com/49373942/65576102-f53d8f80-df79-11e9-9d95-2249c5c3ea9e.JPG)

my pipeline is:

gst-launch-1.0 filesrc location=bbb_sunflower_part1.mp4 ! qtdemux name=demux1 demux1.video_0 ! h264parse ! queue ! omxh264dec ! queue max-size-bytes=0 ! filesink location="output_0.yuv" & gst-launch-1.0 filesrc location=bbb_sunflower_part2.mp4 ! qtdemux name=demux2 demux2.video_0 ! h264parse ! queue ! omxh264dec ! queue max-size-bytes=0 ! filesink location="output_1.yuv" 

The same format has worked for 1080p videos.

Do you have an idea what might cause the problem?

**Comment by hdlguy** [comment]
yildizbilgin,
Sorrry I cannot be much help on video decoding.  I haven't done that myself. Good luck to you.

**Comment by yildizbilgin** [comment]
hdlguy,

Thank you.
