### ISSUE TITLE
I do not see where you are running Ubuntu Desktop linux?

### ISSUE THREAD

**Issue by pkimelman-nxp** [hdlguy/zcu104_ubuntu#4]
I tried your Linaro Debian version but if I try to install Gnome or the Ubuntu desktop, it gets a massive  number of errors. You refer to a build from scratch but then say it does not work. 
So, where or how are you running Desktop Ubuntu on the ZCU104?
I installed Ubuntu and then Ubuntu desktop, but it fails on startx with an error that it cannot load driver "xlnx". Petalinux does not include that as far as I can tell, and it is not standard to any version of Ubuntu. So, I am unclear how you are running Ubuntu Desktop on the ZCU104.
I am using 2019.1 of Petalinux. I see that 2018.2 did not work because of missing files, but 2019.1 is supposed to be valid for this.

**Comment by hdlguy** [comment]
Paul,

I haven't touched that in a while but it is the petalinux flow I still use all the time.  You are running Petalinux 2019.1 and I am using 2019.2 (Vitus) but it should work the same.

I have never tried to install a desktop.  I always work by using ssh to log onto the ZCU104.  I'm willing to work with you if you are still interested.

Pete

________________________________

**Comment by pkimelman-nxp** [comment]
Hi Pete. I installed Ubuntu and booted it up. I then installed the desktop (gnome and all of the apps) and all went fine. Then, I login via ssh -X which sets up the remote Xwindows server so I don't have to worry about HDMI. I then used startx, but it blows up with a segfault because it wants a driver called "xlnx". I cannot see how it could want an HDMI driver (what I assume this is) because this is remote. So, you would expect it to not need anything from the Xilinx board. I note that xterm works! That is, I can run xterm and it shows up on the server that I am ssh-ing in from. But, I do not know why the desktop cannot be started since I do not know what the "xlnx" driver is that it needs (or it seg faults). 
Any help would be much appreciated.

**Comment by hdlguy** [comment]
Paul,

I also had a similar problem just using xterm.  I have never tried to run the graphical desktop like gnome.  I just use ssh. Sorry.

________________________________

**Comment by pkimelman-nxp** [comment]
On AskUbuntu someone said to use gnome-session vs. startx. This yielded a bunch of errors of the form: "X11 connection rejected because of wrong authentication". So, this is maybe hopeful. I have searched on the web and none of the causes listed are mine (ie. my xauth is all good, there is no rc file, etc). So, I am still stuck with no explanation, but maybe am closer to a solution.
As I said, xterm is working for me, as are xedit and xeyes and various other xwindows apps. So, something about Gnome is the issue.

**Comment by hdlguy** [comment]
That sounds hopeful.  If you figure it out I would like to learn what you had to do.

I have run graphical interfaces to linux on Zynq boards before.  I don't know if it was gnome but similar.  I used the HDMI output to a monitor and attached keyboard and mouse. That approach is very similar to what the Raspberry Pi folks do.

FYI, I have installed a sata ssd in the m.2 slot of the ZCU104 and now I boot my OS from there.  I love a non-volatile and fast filesystem.

  Pete

________________________________

**Comment by pkimelman-nxp** [comment]
> That sounds hopeful. If you figure it out I would like to learn what you had to do. I have run 

I will post here as soon as I get an answer. I want to be clear that my intent was to run the Zync board "headless" with the display via ssh -X and Vino. To run on the HDMI with keyboard, one needs to get the Petalinux drivers over I guess - this may have been done on 2019.2. I am assuming someone is likely working on getting that into Debian linux-next for Linaro device-tree; it is a shame that Petalinux is so out of date in terms of kernel and other pieces, as it makes this all a lot harder than it needs to be.
Truthfully, i thought this headless thing would have been as easy as it used to be for such headless systems, but somehow Gnome/Ubuntu-desktop has internal expectations that are not as cleanly divided as they should be. Hopefully this will actually get some of this cleaned up for others doing the same.
One other note: Xilinx has messed up the hardware description/config file model. It should be that I can run Vivado 2019.1 and you can use Petalinux 2019.2 and vice-versa, but that is not the case. It will just not work unless every part of the flow is from the same generation. I would hope that the broader community gets this resolved.

**Comment by hdlguy** [comment]
Paul, I experienced the same with tool version compatibility. I'm not a big fan of Yocto and Petalinux takes that to another level of complexity. Unfortunately, there is almost no alternative.

  Pete

________________________________

**Comment by pkimelman-nxp** [comment]
OK, I have found that I can use remote-desktop but not with Gnome-session due to some bug in xrdb or gnome in Ubuntu 18.04. 
I can use xfce instead and it all works fine. I would hope that whatever bug is stopping gnome-session working is fixed eventually as I prefer it. 
I was not able to use remote X because GNOME has an issue where some parts want to use one scheme and some another in that case. Xrdb uses Xorg and that just works fine. I though I could use Vino and VNC for this, but I do not know how to tell vino to launch the desktop - the instructions I was given segfault. There may be some other VNC which can work but all the instructions I see is from a few years ago, and all complaints about it not working applies to 18.04.
Obviously it would be nice if this were possible since Remote desktop is limiting as a client model.

**Comment by hdlguy** [comment]
> Hi Pete. I installed Ubuntu and booted it up. I then installed the desktop (gnome and all of the apps) and all went fine. Then, I login via ssh -X which sets up the remote Xwindows server so I don't have to worry about HDMI. I then used startx, but it blows up with a segfault because it wants a driver called "xlnx". I cannot see how it could want an HDMI driver (what I assume this is) because this is remote. So, you would expect it to not need anything from the Xilinx board. I note that xterm works! That is, I can run xterm and it shows up on the server that I am ssh-ing in from. But, I do not know why the desktop cannot be started since I do not know what the "xlnx" driver is that it needs (or it seg faults).
> Any help would be much appreciated.
